version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/frontend/web"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/frontend/pwa"
    schedule:
      interval: weekly
