repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3.12
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [sqlalchemy]
        language_version: python3.12

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.10.1
    hooks:
      - id: commitizen
        language_version: python3.12
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        files: ^backend/Dockerfile$

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.14
    hooks:
      - id: tfsec
        args: [infra/terraform]
        pass_filenames: false

  - repo: https://github.com/tenable/terrascan
    rev: v1.19.9
    hooks:
      - id: terraform-pre-commit
        args: [--, infra/terraform]
        pass_filenames: false
