repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3.12
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        additional_dependencies: [sqlalchemy]
        language_version: python3.12

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        language_version: python3.12
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        files: ^backend/Dockerfile$

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.14
    hooks:
      - id: tfsec
        args: [infra/terraform]
        pass_filenames: false

  - repo: https://github.com/tenable/terrascan
    rev: v1.19.9
    hooks:
      - id: terraform-pre-commit
        args: [--, infra/terraform]
        pass_filenames: false
        files: ^infra/terraform/
  - repo: local
    hooks:
      - id: generate-openapi
        name: Generate OpenAPI spec
        entry: make openapi
        language: system
        pass_filenames: false
