version: '3.9'
services:
  db:
    image: timescale/timescaledb:2-postgis-16
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true
    read_only: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    env_file: .env
    security_opt:
      - no-new-privileges:true
    read_only: true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  zookeeper:
    image: bitnami/zookeeper:3.8
    env_file: .env
    security_opt:
      - no-new-privileges:true
    read_only: true
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost $$ZOOKEEPER_CLIENT_PORT | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 5
  kafka:
    image: bitnami/kafka:3
    depends_on:
      - zookeeper
    env_file: .env
    security_opt:
      - no-new-privileges:true
    read_only: true
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis
      - kafka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5

  bank-bridge:
    build:
      context: .
      dockerfile: services/bank_bridge/Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512Mi

  bank-bridge-consumer:
    build:
      context: .
      dockerfile: services/bank_bridge/consumer.Dockerfile
    env_file: .env
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512Mi
volumes:
  db_data:
