[tool.black]
line-length = 88
target-version = ['py312']

[tool.ruff]
target-version = 'py312'
line-length = 88

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"

