"""add bank tokens

Revision ID: c3cf30754da7
Revises: 8d4fb5d8f3de
Create Date: 2025-06-30 09:45:49.055901

"""

from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3cf30754da7"
down_revision: Union[str, Sequence[str], None] = "8d4fb5d8f3de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "bank"),
    )
    op.create_index(op.f("ix_bank_tokens_id"), "bank_tokens", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bank_tokens_id"), table_name="bank_tokens")
    op.drop_table("bank_tokens")
    # ### end Alembic commands ###
