apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-machine-rollout
spec:
  project: default
  source:
    repoURL: https://github.com/example/budget-machine
    targetRevision: HEAD
    path: deploy/helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: budget-machine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
