name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r backend/requirements-dev.txt
          pip install ruff==0.12.1 black==25.1.0 pytest
      - name: Ruff lint
        run: ruff check --output-format=github .
      - name: Black check
        run: black --check .
      - name: Mypy check
        run: mypy backend/app
      - name: Run tests
        run: pytest backend/tests

  codeql:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
      - uses: github/codeql-action/analyze@v3
