name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt pre-commit
      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --color always --all-files
      - name: Run tests
        run: pytest -q
