# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ledger.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

from google.protobuf import (
    timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2,  # noqa: F401
)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12proto/ledger.proto\x12\x06ledger\x1a\x1fgoogle/protobuf/timestamp.proto"T\n\x07Posting\x12\x16\n\x06\x61mount\x18\x01 \x01(\x01R\x06\x61mount\x12\x12\n\x04side\x18\x02 \x01(\tR\x04side\x12\x1d\n\naccount_id\x18\x03 \x01(\tR\taccountId"\x9c\x02\n\x10PostEntryRequest\x12\x14\n\x05payee\x18\x01 \x01(\tR\x05payee\x12\x12\n\x04note\x18\x02 \x01(\tR\x04note\x12\x1f\n\x0b\x65xternal_id\x18\x03 \x01(\tR\nexternalId\x12\x1f\n\x0b\x63\x61tegory_id\x18\x04 \x01(\tR\ncategoryId\x12\x37\n\tposted_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x08postedAt\x12+\n\x08postings\x18\x06 \x03(\x0b\x32\x0f.ledger.PostingR\x08postings\x12\x1d\n\naccount_id\x18\x07 \x01(\tR\taccountId\x12\x17\n\x07user_id\x18\x08 \x01(\tR\x06userId"\xd3\x01\n\x03Txn\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x37\n\tposted_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x08postedAt\x12\x14\n\x05payee\x18\x03 \x01(\tR\x05payee\x12\x12\n\x04note\x18\x04 \x01(\tR\x04note\x12\x1f\n\x0b\x65xternal_id\x18\x05 \x01(\tR\nexternalId\x12\x1f\n\x0b\x63\x61tegory_id\x18\x06 \x01(\tR\ncategoryId\x12\x17\n\x07user_id\x18\x07 \x01(\tR\x06userId"\x17\n\x05TxnId\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id"[\n\x0e\x42\x61lanceRequest\x12\x1d\n\naccount_id\x18\x01 \x01(\tR\taccountId\x12*\n\x02\x61t\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x02\x61t")\n\x0f\x42\x61lanceResponse\x12\x16\n\x06\x61mount\x18\x01 \x01(\x01R\x06\x61mount"\x8e\x01\n\rStreamRequest\x12\x1d\n\naccount_id\x18\x01 \x01(\tR\taccountId\x12\x30\n\x05start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x05start\x12,\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x03\x65nd2\xb8\x01\n\rLedgerService\x12\x34\n\tPostEntry\x12\x18.ledger.PostEntryRequest\x1a\r.ledger.TxnId\x12=\n\nGetBalance\x12\x16.ledger.BalanceRequest\x1a\x17.ledger.BalanceResponse\x12\x32\n\nStreamTxns\x12\x15.ledger.StreamRequest\x1a\x0b.ledger.Txn0\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.ledger_pb2", globals())
if not _descriptor._USE_C_DESCRIPTORS:

    DESCRIPTOR._options = None
    _POSTING._serialized_start = 63  # noqa: F821
    _POSTING._serialized_end = 147  # noqa: F821
    _POSTENTRYREQUEST._serialized_start = 150  # noqa: F821
    _POSTENTRYREQUEST._serialized_end = 434  # noqa: F821
    _TXN._serialized_start = 437  # noqa: F821
    _TXN._serialized_end = 648  # noqa: F821
    _TXNID._serialized_start = 650  # noqa: F821
    _TXNID._serialized_end = 673  # noqa: F821
    _BALANCEREQUEST._serialized_start = 675  # noqa: F821
    _BALANCEREQUEST._serialized_end = 766  # noqa: F821
    _BALANCERESPONSE._serialized_start = 768  # noqa: F821
    _BALANCERESPONSE._serialized_end = 809  # noqa: F821
    _STREAMREQUEST._serialized_start = 812  # noqa: F821
    _STREAMREQUEST._serialized_end = 954  # noqa: F821
    _LEDGERSERVICE._serialized_start = 957  # noqa: F821
    _LEDGERSERVICE._serialized_end = 1141  # noqa: F821
# @@protoc_insertion_point(module_scope)
