# ruff: noqa
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ledger.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "ledger.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cledger.proto\x12\x06ledger\x1a\x1fgoogle/protobuf/timestamp.proto";\n\x07Posting\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\t"\xd6\x01\n\x10PostEntryRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0b\x63\x61tegory_id\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12!\n\x08postings\x18\x06 \x03(\x0b\x32\x0f.ledger.Posting\x12\x12\n\naccount_id\x18\x07 \x01(\t\x12\x0f\n\x07user_id\x18\x08 \x01(\t"\xce\x01\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x12\n\namount_rub\x18\x04 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x13\n\x0b\x63\x61tegory_id\x18\x06 \x01(\t\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\naccount_id\x18\x08 \x01(\t\x12\x0f\n\x07user_id\x18\t \x01(\t"O\n\x11GetBalanceRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12&\n\x02\x61t\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"\x19\n\x07\x42\x61lance\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01"{\n\x11StreamTxnsRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12)\n\x05start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xc5\x01\n\rLedgerService\x12:\n\tPostEntry\x12\x18.ledger.PostEntryRequest\x1a\x13.ledger.Transaction\x12\x38\n\nGetBalance\x12\x19.ledger.GetBalanceRequest\x1a\x0f.ledger.Balance\x12>\n\nStreamTxns\x12\x19.ledger.StreamTxnsRequest\x1a\x13.ledger.Transaction0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ledger_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_POSTING"]._serialized_start = 57
    _globals["_POSTING"]._serialized_end = 116
    _globals["_POSTENTRYREQUEST"]._serialized_start = 119
    _globals["_POSTENTRYREQUEST"]._serialized_end = 333
    _globals["_TRANSACTION"]._serialized_start = 336
    _globals["_TRANSACTION"]._serialized_end = 542
    _globals["_GETBALANCEREQUEST"]._serialized_start = 544
    _globals["_GETBALANCEREQUEST"]._serialized_end = 623
    _globals["_BALANCE"]._serialized_start = 625
    _globals["_BALANCE"]._serialized_end = 650
    _globals["_STREAMTXNSREQUEST"]._serialized_start = 652
    _globals["_STREAMTXNSREQUEST"]._serialized_end = 775
    _globals["_LEDGERSERVICE"]._serialized_start = 778
    _globals["_LEDGERSERVICE"]._serialized_end = 975
# @@protoc_insertion_point(module_scope)
